name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - uses: oracle-actions/setup-java@v1
        if: ${{ vars.GRADLE_JAVA_VERSION != vars.JAVA_VERSION }}
        with:
          website: jdk.java.net
          release: ${{ vars.GRADLE_JAVA_VERSION }}

      - run: |
          printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
          java --version
        if: ${{ vars.GRADLE_JAVA_VERSION != vars.JAVA_VERSION }}

      - uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ vars.JAVA_VERSION }}

      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
        if: ${{ vars.GRADLE_JAVA_VERSION == vars.JAVA_VERSION }}

      - name: Generate Source, Check & Publish
        run: |
          printf "\norg.gradle.java.installations.paths=%s" "$JAVA_HOME" >> gradle.properties
          java --version
          ./genSrc.sh --tjv="${{ vars.JAVA_VERSION }}" --tl=2 --bdm=200 --nt=5 --rpc="${{ secrets.RPC_URL }}"
          ./gradlew -PtargetJava=${{ vars.JAVA_VERSION }} --stacktrace check publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SAVA_USER: ${{ secrets.GPR_USER }}
          GITHUB_SAVA_TOKEN: ${{ secrets.GPR_TOKEN }}
